# .circleci/config.yml
version: 2
jobs:
  build-and-test:
    macos:
      xcode: "10.2"
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: run_tweetmd_tests
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Install CocoaPods
          command: pod install --verbose
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test